"""DeltaDetector — file/directory SHA-256 hashing and changed-file detection.

Extracted from ``okfgraph.router.OKFRouter`` section:
  - delta detection (router.py 714–953)
"""

import hashlib
from pathlib import Path
from typing import Dict, List, Tuple

import logging

logger = logging.getLogger(__name__)


class DeltaDetector:
    def __init__(self, conn, bundle_root):
        self.conn = conn
        self.bundle_root = Path(bundle_root).resolve()

    def _file_hash(self, file_path: Path) -> str: ...
    def _compute_directory_hash(self, dir_path: Path) -> str: ...
    def _compute_directory_hash_with_files(self, dir_path: Path) -> Tuple[str, List[str]]: ...
    def _load_directory_hashes(self) -> Dict[str, Dict]: ...
    def _store_directory_hashes(self, hashes: Dict[str, Dict]) -> None: ...
    def _changed_directories(self, source_files: List[Path]) -> Tuple[List[Path], List[str]]: ...
    def _store_file_hashes(self, hashes: Dict[str, str]) -> None: ...
    def _load_file_hashes(self) -> Dict[str, str]: ...
    def _load_file_hash_concept_ids(self) -> Dict[str, str]: ...
    def _changed_files(self, source_files: List[Path]) -> Tuple[List[Path], List[str]]: ...
